services:
  - type: web
    name: pdf-qa-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py  # Using python directly to run main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT  # This will be overridden by the Render dashboard setting
        value: 8080
    healthCheckPath: /